# Generated by Django 6.0 on 2026-01-01 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('racial', 'Racial'), ('class', 'De Classe'), ('magic', 'Magia Arcana'), ('general', 'Geral'), ('path', 'Caminho'), ('support', 'Suporte')], default='general', max_length=20)),
                ('mana_cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='Custo de Mana')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name='Dificuldade')),
                ('casting_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempo de Execução')),
                ('range_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alcance/Área')),
                ('requirements_text', models.TextField(blank=True, help_text="Texto descritivo dos requisitos (ex: 'Força 3')")),
            ],
            options={
                'verbose_name': 'Habilidade/Magia',
                'verbose_name_plural': 'Habilidades e Magias',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Peso Base (kg)')),
                ('price', models.IntegerField(default=0, verbose_name='Preço Base (Cobre)')),
                ('is_stackable', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('weapon', 'Arma'), ('armor', 'Armadura/Escudo'), ('consumable', 'Consumível'), ('gear', 'Equipamento Geral')], default='gear', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('benefit_text', models.TextField(verbose_name='Benefício Mecânico')),
                ('requirements_text', models.TextField(blank=True)),
                ('starting_equipment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('bonus_str', models.IntegerField(default=0)),
                ('bonus_agi', models.IntegerField(default=0)),
                ('bonus_int', models.IntegerField(default=0)),
                ('bonus_wil', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('creature_type', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('strength', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('will', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10, verbose_name='Vida')),
                ('mana', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('attacks_data', models.JSONField(blank=True, default=list)),
                ('abilities_data', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('cost_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('skill_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('speakers', models.CharField(blank=True, max_length=255, verbose_name='Falantes Típicos')),
                ('is_exotic', models.BooleanField(default=False)),
                ('script', models.CharField(blank=True, max_length=50, verbose_name='Alfabeto')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('weight_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('damage_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('special_rules', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('initial_str', models.IntegerField(default=0, verbose_name='Força Inicial')),
                ('initial_agi', models.IntegerField(default=0, verbose_name='Agilidade Inicial')),
                ('initial_int', models.IntegerField(default=0, verbose_name='Inteligência Inicial')),
                ('initial_wil', models.IntegerField(default=0, verbose_name='Vontade Inicial')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='SpiritAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Informações sobre rolagens e mecânicas do espírito animal', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Espírito Animal',
                'verbose_name_plural': 'Espíritos Animais',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.item')),
                ('defense_bonus', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('is_heavy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Armadura ou Escudo',
                'verbose_name_plural': 'Armaduras e Escudos',
            },
            bases=('core.item',),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.item')),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('charges', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Consumível',
                'verbose_name_plural': 'Consumíveis',
            },
            bases=('core.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.item')),
                ('damage', models.IntegerField(default=0)),
                ('damage_type', models.CharField(blank=True, max_length=50)),
                ('grip', models.CharField(blank=True, max_length=50)),
                ('min_strength', models.IntegerField(default=0)),
                ('defense_bonus', models.BooleanField(default=False)),
                ('is_throwable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
            },
            bases=('core.item',),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True, verbose_name='Biografia')),
                ('appearance', models.TextField(blank=True, verbose_name='Aparência')),
                ('personality', models.TextField(blank=True, verbose_name='Personalidade')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('will', models.IntegerField(default=0)),
                ('hp_max', models.IntegerField(default=10)),
                ('hp_current', models.IntegerField(default=10)),
                ('mana_max', models.IntegerField(default=0)),
                ('mana_current', models.IntegerField(default=0)),
                ('coin_copper', models.IntegerField(default=0, verbose_name='Cobre')),
                ('coin_silver', models.IntegerField(default=0, verbose_name='Prata')),
                ('coin_gold', models.IntegerField(default=0, verbose_name='Ouro')),
                ('extra_carry_capacity', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Carga Extra (Kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.background')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.characterclass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.race')),
                ('spirit_animal', models.ForeignKey(blank=True, help_text='Espírito animal vinculado ao personagem (apenas um)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.spiritanimal', verbose_name='Espírito Animal')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ability')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='core.character')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAvailableAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ability')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_skills', to='core.characterclass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=100)),
                ('current_hp', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='core.character')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.creature')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.character')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.language')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.itemquality')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='RaceInnateAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ability')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innate_abilities', to='core.race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceLore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming_rules_html', models.TextField(verbose_name='Regras de Nomes (HTML)')),
                ('male_names', models.TextField(blank=True, help_text='Lista separada por vírgulas ou quebras')),
                ('female_names', models.TextField(blank=True)),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lore', to='core.race')),
            ],
        ),
    ]
